import type { BirFormCoord } from "./types";

// Generated by /dev/coord-picker

export const COORDS_1701Q: Record<string, BirFormCoord> = {
  "part1_year": {
    "page": 1,
    "x": 95,
    "y": 830,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_quarter_first": {
    "page": 1,
    "x": 195.5,
    "y": 835.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_quarter_second": {
    "page": 1,
    "x": 239.5,
    "y": 836,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_quarter_third": {
    "page": 1,
    "x": 297.5,
    "y": 836,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_amended_yes": {
    "page": 1,
    "x": 428.5,
    "y": 835,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_amended_no": {
    "page": 1,
    "x": 470.5,
    "y": 833.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_sheets_attached": {
    "page": 1,
    "x": 574,
    "y": 830,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_tin": {
    "page": 1,
    "x": 203,
    "y": 798,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_rdo_code": {
    "page": 1,
    "x": 540.5,
    "y": 798,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_taxpayer_type_single_proprietor": {
    "page": 1,
    "x": 120,
    "y": 785.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_taxpayer_type_professional": {
    "page": 1,
    "x": 227,
    "y": 785.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_taxpayer_type_estate": {
    "page": 1,
    "x": 329.5,
    "y": 785,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_taxpayer_type_trust": {
    "page": 1,
    "x": 414,
    "y": 785,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_atc_ii015": {
    "page": 1,
    "x": 163.5,
    "y": 753.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_atc_ii017": {
    "page": 1,
    "x": 309.5,
    "y": 755,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_atc_ii016": {
    "page": 1,
    "x": 471,
    "y": 754,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_taxpayer_name": {
    "page": 1,
    "x": 22.5,
    "y": 726.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_registered_address": {
    "page": 1,
    "x": 22.5,
    "y": 699,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_zip_code": {
    "page": 1,
    "x": 541,
    "y": 681,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_date_of_birth": {
    "page": 1,
    "x": 22.5,
    "y": 654,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_email": {
    "page": 1,
    "x": 133.5,
    "y": 654,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_citizenship": {
    "page": 1,
    "x": 22,
    "y": 626,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_foreign_tax_number": {
    "page": 1,
    "x": 249.5,
    "y": 626.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_claiming_foreign_yes": {
    "page": 1,
    "x": 510,
    "y": 626,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_claiming_foreign_no": {
    "page": 1,
    "x": 557,
    "y": 626,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_tax_rate_8pct": {
    "page": 1,
    "x": 67,
    "y": 578.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_tax_rate_graduated": {
    "page": 1,
    "x": 66,
    "y": 599,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_tax_rate_itemized": {
    "page": 1,
    "x": 234,
    "y": 600.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_tax_rate_osd": {
    "page": 1,
    "x": 364,
    "y": 600,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_tax_due": {
    "page": 1,
    "x": 369.5,
    "y": 340.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_less_tax_credits": {
    "page": 1,
    "x": 368.5,
    "y": 325.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_tax_payable": {
    "page": 1,
    "x": 369,
    "y": 309.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_total_penalties": {
    "page": 1,
    "x": 369,
    "y": 293.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_total_amount_payable": {
    "page": 1,
    "x": 369.5,
    "y": 278,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_aggregate_amount_payable": {
    "page": 1,
    "x": 428,
    "y": 261.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part4_cash_bank_debit": {
    "page": 1,
    "x": 124,
    "y": 155,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part4_check": {
    "page": 1,
    "x": 124,
    "y": 139,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part4_tax_debit_memo": {
    "page": 1,
    "x": 211,
    "y": 124.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "part4_others": {
    "page": 1,
    "x": 23.5,
    "y": 97,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_sales": {
    "page": 2,
    "x": 363.5,
    "y": 766.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "page2_tin": {
    "page": 2,
    "x": 20.5,
    "y": 829.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "page2_taxpayer_lastname": {
    "page": 2,
    "x": 213.5,
    "y": 830,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_cost_of_sales": {
    "page": 2,
    "x": 362,
    "y": 750.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_gross_income": {
    "page": 2,
    "x": 363.5,
    "y": 736,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_itemized_deductions": {
    "page": 2,
    "x": 362.5,
    "y": 708,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_osd": {
    "page": 2,
    "x": 362.5,
    "y": 680,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_net_income_this_quarter": {
    "page": 2,
    "x": 362.5,
    "y": 664.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_prev_quarter_taxable": {
    "page": 2,
    "x": 362.5,
    "y": 648.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_non_operating_income": {
    "page": 2,
    "x": 362.5,
    "y": 631.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_gpp_income": {
    "page": 2,
    "x": 362,
    "y": 616.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_total_taxable_to_date": {
    "page": 2,
    "x": 362,
    "y": 599.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_tax_due": {
    "page": 2,
    "x": 363,
    "y": 584,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched2_sales": {
    "page": 2,
    "x": 363,
    "y": 553.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched2_non_operating_income": {
    "page": 2,
    "x": 363.5,
    "y": 536,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched2_total_income_quarter": {
    "page": 2,
    "x": 363,
    "y": 520.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched2_prev_quarter_taxable": {
    "page": 2,
    "x": 363,
    "y": 503.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched2_cumulative_taxable": {
    "page": 2,
    "x": 362,
    "y": 488,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched2_less_250k": {
    "page": 2,
    "x": 362.5,
    "y": 471,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched2_taxable_to_date": {
    "page": 2,
    "x": 363.5,
    "y": 454.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched2_tax_due": {
    "page": 2,
    "x": 362.5,
    "y": 437.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched3_prior_year_excess_credits": {
    "page": 2,
    "x": 363.5,
    "y": 407.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched3_prev_quarter_payments": {
    "page": 2,
    "x": 363,
    "y": 390.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched3_prev_quarter_cwt": {
    "page": 2,
    "x": 363,
    "y": 374.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched3_current_quarter_cwt": {
    "page": 2,
    "x": 363,
    "y": 358.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched3_prev_return_payment": {
    "page": 2,
    "x": 363,
    "y": 344,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched3_foreign_tax_credits": {
    "page": 2,
    "x": 362.5,
    "y": 327.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched3_other_credits": {
    "page": 2,
    "x": 362.5,
    "y": 310,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched3_total_credits": {
    "page": 2,
    "x": 362,
    "y": 295.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched3_tax_payable_overpayment": {
    "page": 2,
    "x": 362.5,
    "y": 275.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched4_surcharge": {
    "page": 2,
    "x": 363,
    "y": 245,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched4_interest": {
    "page": 2,
    "x": 362.5,
    "y": 227,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched4_compromise": {
    "page": 2,
    "x": 363,
    "y": 213,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched4_total_penalties": {
    "page": 2,
    "x": 364,
    "y": 198,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  },
  "sched4_total_amount_payable": {
    "page": 2,
    "x": 362,
    "y": 176.5,
    "fontSize": 10,
    "maxWidth": 100,
    "align": "left"
  }
};
