import type { BirFormCoord } from "./types";

// Generated by /dev/coord-picker

export const COORDS_1701A: Record<string, BirFormCoord> = {
  "part1_year": {
    "page": 1,
    "x": 120,
    "y": 818.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_amended_yes": {
    "page": 1,
    "x": 305.5,
    "y": 820,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_short_period_yes": {
    "page": 1,
    "x": 500,
    "y": 819.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_tin": {
    "page": 1,
    "x": 35.5,
    "y": 775,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_rdo_code": {
    "page": 1,
    "x": 304,
    "y": 774,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_taxpayer_type_single_proprietor": {
    "page": 1,
    "x": 400.5,
    "y": 775.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_taxpayer_type_professional": {
    "page": 1,
    "x": 514.5,
    "y": 774,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_atc": {
    "page": 1,
    "x": 165.5,
    "y": 742.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_taxpayer_name": {
    "page": 1,
    "x": 21.5,
    "y": 712.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_registered_address": {
    "page": 1,
    "x": 21.5,
    "y": 682,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_zip_code": {
    "page": 1,
    "x": 545.5,
    "y": 664.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_date_of_birth": {
    "page": 1,
    "x": 21.5,
    "y": 636.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_email": {
    "page": 1,
    "x": 132.5,
    "y": 636,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_citizenship": {
    "page": 1,
    "x": 21.5,
    "y": 607,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_claiming_foreign_yes": {
    "page": 1,
    "x": 276.5,
    "y": 606,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_foreign_tax_number": {
    "page": 1,
    "x": 364,
    "y": 609,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_contact_number": {
    "page": 1,
    "x": 21,
    "y": 577,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_civil_status": {
    "page": 1,
    "x": 245.5,
    "y": 580.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_filing_status": {
    "page": 1,
    "x": 438,
    "y": 561.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_tax_rate": {
    "page": 1,
    "x": 276,
    "y": 542,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_tax_due": {
    "page": 1,
    "x": 366.5,
    "y": 492.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_surcharge": {
    "page": 1,
    "x": 366,
    "y": 402,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_interest": {
    "page": 1,
    "x": 365,
    "y": 383,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_compromise": {
    "page": 1,
    "x": 366,
    "y": 365,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_total_penalties": {
    "page": 1,
    "x": 366,
    "y": 347,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_total_amount_payable": {
    "page": 1,
    "x": 365,
    "y": 328.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_aggregate": {
    "page": 1,
    "x": 426.5,
    "y": 311.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_attachments": {
    "page": 1,
    "x": 575.5,
    "y": 217.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_cash_amount": {
    "page": 1,
    "x": 486,
    "y": 168,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_check_amount": {
    "page": 1,
    "x": 485.5,
    "y": 149,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_tax_debit_amount": {
    "page": 1,
    "x": 486,
    "y": 130.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_others_amount": {
    "page": 1,
    "x": 486,
    "y": 102,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4b_sales": {
    "page": 2,
    "x": 363.5,
    "y": 574,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4b_less_returns": {
    "page": 2,
    "x": 363,
    "y": 558,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4b_net_sales": {
    "page": 2,
    "x": 363,
    "y": 539.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4b_other_income_1": {
    "page": 2,
    "x": 362.5,
    "y": 512,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4b_other_income_2": {
    "page": 2,
    "x": 362.5,
    "y": 494,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4b_total_other": {
    "page": 2,
    "x": 363.5,
    "y": 475,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4b_total_taxable": {
    "page": 2,
    "x": 362,
    "y": 458.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4b_less_250k": {
    "page": 2,
    "x": 363.5,
    "y": 439,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4b_taxable_loss": {
    "page": 2,
    "x": 363,
    "y": 423.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4b_tax_due": {
    "page": 2,
    "x": 362.5,
    "y": 405.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4c_prior_year_credits": {
    "page": 2,
    "x": 364,
    "y": 377,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4c_q1q3_payments": {
    "page": 2,
    "x": 364,
    "y": 360.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4c_q1q3_cwt": {
    "page": 2,
    "x": 363,
    "y": 346,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4c_q4_cwt": {
    "page": 2,
    "x": 363.5,
    "y": 329.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4c_prior_tax_paid": {
    "page": 2,
    "x": 364.5,
    "y": 313,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4c_foreign_tax_credits": {
    "page": 2,
    "x": 364,
    "y": 298,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4c_other_credits": {
    "page": 2,
    "x": 364.5,
    "y": 281.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4c_total_credits": {
    "page": 2,
    "x": 364,
    "y": 265.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part4c_net_tax_payable": {
    "page": 2,
    "x": 363.5,
    "y": 249,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  }
};
