import type { BirFormCoord } from "./types";

// AUTO-GENERATED by scripts/extract-1701a-coords.ts.
// Visual verification: see tmp/1701A-coords-check.pdf (and .png if render succeeded).
// Coordinates are pdf-lib convention: origin = bottom-left, y counts up.
// Page size: 612 x 936 pt (US Letter). Reviewed: pending visual check.

export const COORDS_1701A: Record<string, BirFormCoord> = {
  "part1_year": {
    "page": 1,
    "x": 360,
    "y": 815.74,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_amended_yes": {
    "page": 1,
    "x": 283,
    "y": 815.74,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_short_period_yes": {
    "page": 1,
    "x": 473,
    "y": 815.74,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_tin": {
    "page": 1,
    "x": 200,
    "y": 785.62,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_rdo_code": {
    "page": 1,
    "x": 340,
    "y": 785.62,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_atc": {
    "page": 1,
    "x": 200,
    "y": 752.86,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_taxpayer_type_single_proprietor": {
    "page": 1,
    "x": 375,
    "y": 785.62,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_taxpayer_type_professional": {
    "page": 1,
    "x": 535,
    "y": 785.62,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_taxpayer_name": {
    "page": 1,
    "x": 200,
    "y": 723.34,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_registered_address": {
    "page": 1,
    "x": 200,
    "y": 694.78,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_zip_code": {
    "page": 1,
    "x": 555,
    "y": 662.35,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_date_of_birth": {
    "page": 1,
    "x": 130,
    "y": 647.83,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_email": {
    "page": 1,
    "x": 400,
    "y": 647.83,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_citizenship": {
    "page": 1,
    "x": 200,
    "y": 619.27,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_claiming_foreign_yes": {
    "page": 1,
    "x": 322,
    "y": 619.27,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_foreign_tax_number": {
    "page": 1,
    "x": 455,
    "y": 619.27,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_contact_number": {
    "page": 1,
    "x": 200,
    "y": 590.11,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_civil_status": {
    "page": 1,
    "x": 380,
    "y": 590.11,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_filing_status": {
    "page": 1,
    "x": 410,
    "y": 557.83,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_tax_rate": {
    "page": 1,
    "x": 200,
    "y": 542.83,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_tax_due": {
    "page": 1,
    "x": 440,
    "y": 491.59,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_surcharge": {
    "page": 1,
    "x": 450,
    "y": 400.25,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_interest": {
    "page": 1,
    "x": 450,
    "y": 382.01,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_compromise": {
    "page": 1,
    "x": 450,
    "y": 363.77,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_total_penalties": {
    "page": 1,
    "x": 450,
    "y": 345.53,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_total_amount_payable": {
    "page": 1,
    "x": 450,
    "y": 327.29,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_aggregate": {
    "page": 1,
    "x": 450,
    "y": 309.05,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_attachments": {
    "page": 1,
    "x": 575,
    "y": 215.54,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_cash_amount": {
    "page": 1,
    "x": 560,
    "y": 164.42,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_check_amount": {
    "page": 1,
    "x": 560,
    "y": 146.18,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_tax_debit_amount": {
    "page": 1,
    "x": 560,
    "y": 127.94,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_others_amount": {
    "page": 1,
    "x": 560,
    "y": 113.4,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4b_sales": {
    "page": 2,
    "x": 440,
    "y": 571.75,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4b_less_returns": {
    "page": 2,
    "x": 440,
    "y": 554.83,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4b_net_sales": {
    "page": 2,
    "x": 440,
    "y": 537.91,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4b_other_income_1": {
    "page": 2,
    "x": 440,
    "y": 509.47,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4b_other_income_2": {
    "page": 2,
    "x": 440,
    "y": 491.23,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4b_total_other": {
    "page": 2,
    "x": 440,
    "y": 473.57,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4b_total_taxable": {
    "page": 2,
    "x": 440,
    "y": 456.65,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4b_less_250k": {
    "page": 2,
    "x": 440,
    "y": 442.73,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4b_taxable_loss": {
    "page": 2,
    "x": 440,
    "y": 420.29,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4b_tax_due": {
    "page": 2,
    "x": 440,
    "y": 403.25,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4c_prior_year_credits": {
    "page": 2,
    "x": 440,
    "y": 374.93,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4c_q1q3_payments": {
    "page": 2,
    "x": 440,
    "y": 359.09,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4c_q1q3_cwt": {
    "page": 2,
    "x": 440,
    "y": 343.13,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4c_q4_cwt": {
    "page": 2,
    "x": 440,
    "y": 327.17,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4c_prior_tax_paid": {
    "page": 2,
    "x": 440,
    "y": 311.21,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4c_foreign_tax_credits": {
    "page": 2,
    "x": 440,
    "y": 295.22,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4c_other_credits": {
    "page": 2,
    "x": 440,
    "y": 279.26,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4c_total_credits": {
    "page": 2,
    "x": 440,
    "y": 263.3,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4c_net_tax_payable": {
    "page": 2,
    "x": 440,
    "y": 246.38,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  }
};
