import type { BirFormCoord } from "./types";

// AUTO-GENERATED by scripts/extract-1701q-coords.ts.
// Visual verification: see tmp/1701Q-coords-check.pdf (and .png if render succeeded).
// Coordinates are pdf-lib convention: origin = bottom-left, y counts up.
// Page size: 612 x 936 pt (US Letter). Reviewed: pending visual check.

export const COORDS_1701Q: Record<string, BirFormCoord> = {
  "part1_year": {
    "page": 1,
    "x": 360,
    "y": 831.1,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_quarter_first": {
    "page": 1,
    "x": 185,
    "y": 831.1,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_quarter_second": {
    "page": 1,
    "x": 232,
    "y": 831.1,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_quarter_third": {
    "page": 1,
    "x": 285,
    "y": 831.1,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_amended_yes": {
    "page": 1,
    "x": 446,
    "y": 831.1,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_amended_no": {
    "page": 1,
    "x": 480,
    "y": 831.1,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_sheets_attached": {
    "page": 1,
    "x": 555,
    "y": 836,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_tin": {
    "page": 1,
    "x": 285,
    "y": 798.58,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_rdo_code": {
    "page": 1,
    "x": 340,
    "y": 798.58,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_taxpayer_type_single_proprietor": {
    "page": 1,
    "x": 110,
    "y": 782,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_taxpayer_type_professional": {
    "page": 1,
    "x": 220,
    "y": 782,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_taxpayer_type_estate": {
    "page": 1,
    "x": 320,
    "y": 782,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_taxpayer_type_trust": {
    "page": 1,
    "x": 410,
    "y": 782,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_atc_ii015": {
    "page": 1,
    "x": 200,
    "y": 764.98,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_atc_ii017": {
    "page": 1,
    "x": 350,
    "y": 764.98,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_atc_ii016": {
    "page": 1,
    "x": 510,
    "y": 764.98,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_taxpayer_name": {
    "page": 1,
    "x": 285,
    "y": 736.54,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_registered_address": {
    "page": 1,
    "x": 285,
    "y": 709.06,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_zip_code": {
    "page": 1,
    "x": 555,
    "y": 678.58,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_date_of_birth": {
    "page": 1,
    "x": 130,
    "y": 664.51,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_email": {
    "page": 1,
    "x": 400,
    "y": 664.51,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_citizenship": {
    "page": 1,
    "x": 200,
    "y": 637.15,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_foreign_tax_number": {
    "page": 1,
    "x": 470,
    "y": 637.15,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_claiming_foreign_yes": {
    "page": 1,
    "x": 534,
    "y": 637.15,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_claiming_foreign_no": {
    "page": 1,
    "x": 570,
    "y": 637.15,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_tax_rate_8pct": {
    "page": 1,
    "x": 30,
    "y": 574,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_tax_rate_graduated": {
    "page": 1,
    "x": 30,
    "y": 599,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_tax_rate_itemized": {
    "page": 1,
    "x": 240,
    "y": 599,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_tax_rate_osd": {
    "page": 1,
    "x": 370,
    "y": 599,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_tax_due": {
    "page": 1,
    "x": 460,
    "y": 338.57,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_less_tax_credits": {
    "page": 1,
    "x": 460,
    "y": 322.61,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_tax_payable": {
    "page": 1,
    "x": 460,
    "y": 306.65,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_total_penalties": {
    "page": 1,
    "x": 460,
    "y": 290.66,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_total_amount_payable": {
    "page": 1,
    "x": 460,
    "y": 274.82,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_aggregate_amount_payable": {
    "page": 1,
    "x": 460,
    "y": 258.86,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4_cash_bank_debit": {
    "page": 1,
    "x": 560,
    "y": 152.42,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4_check": {
    "page": 1,
    "x": 560,
    "y": 136.46,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4_tax_debit_memo": {
    "page": 1,
    "x": 560,
    "y": 120.48,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part4_others": {
    "page": 1,
    "x": 560,
    "y": 107.04,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_sales": {
    "page": 2,
    "x": 460,
    "y": 763.78,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_cost_of_sales": {
    "page": 2,
    "x": 460,
    "y": 747.82,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_gross_income": {
    "page": 2,
    "x": 460,
    "y": 731.86,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_itemized_deductions": {
    "page": 2,
    "x": 460,
    "y": 705.1,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_osd": {
    "page": 2,
    "x": 460,
    "y": 678.34,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_net_income_this_quarter": {
    "page": 2,
    "x": 460,
    "y": 662.35,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_prev_quarter_taxable": {
    "page": 2,
    "x": 460,
    "y": 646.39,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_non_operating_income": {
    "page": 2,
    "x": 460,
    "y": 630.43,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_gpp_income": {
    "page": 2,
    "x": 460,
    "y": 613.99,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_total_taxable_to_date": {
    "page": 2,
    "x": 460,
    "y": 597.55,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_tax_due": {
    "page": 2,
    "x": 460,
    "y": 581.59,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched2_sales": {
    "page": 2,
    "x": 460,
    "y": 550.15,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched2_non_operating_income": {
    "page": 2,
    "x": 460,
    "y": 534.19,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched2_total_income_quarter": {
    "page": 2,
    "x": 460,
    "y": 518.23,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched2_prev_quarter_taxable": {
    "page": 2,
    "x": 460,
    "y": 502.27,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched2_cumulative_taxable": {
    "page": 2,
    "x": 460,
    "y": 486.29,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched2_less_250k": {
    "page": 2,
    "x": 460,
    "y": 470,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched2_taxable_to_date": {
    "page": 2,
    "x": 460,
    "y": 453.29,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched2_tax_due": {
    "page": 2,
    "x": 460,
    "y": 436.85,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched3_prior_year_excess_credits": {
    "page": 2,
    "x": 460,
    "y": 404.81,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched3_prev_quarter_payments": {
    "page": 2,
    "x": 460,
    "y": 388.97,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched3_prev_quarter_cwt": {
    "page": 2,
    "x": 460,
    "y": 373.01,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched3_current_quarter_cwt": {
    "page": 2,
    "x": 460,
    "y": 357.05,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched3_prev_return_payment": {
    "page": 2,
    "x": 460,
    "y": 341.09,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched3_foreign_tax_credits": {
    "page": 2,
    "x": 460,
    "y": 325.13,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched3_other_credits": {
    "page": 2,
    "x": 460,
    "y": 309.17,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched3_total_credits": {
    "page": 2,
    "x": 460,
    "y": 293.18,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched3_tax_payable_overpayment": {
    "page": 2,
    "x": 460,
    "y": 273.62,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched4_surcharge": {
    "page": 2,
    "x": 460,
    "y": 242.06,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched4_interest": {
    "page": 2,
    "x": 460,
    "y": 226.1,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched4_compromise": {
    "page": 2,
    "x": 460,
    "y": 210.14,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched4_total_penalties": {
    "page": 2,
    "x": 460,
    "y": 194.18,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched4_total_amount_payable": {
    "page": 2,
    "x": 460,
    "y": 174.62,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  }
};
