import type { BirFormCoord } from "./types";

// Generated by /dev/coord-picker

export const COORDS_2551Q: Record<string, BirFormCoord> = {
  "header_calendar": {
    "page": 1,
    "x": 91.5,
    "y": 818,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "center"
  },
  "header_fiscal": {
    "page": 1,
    "x": 164,
    "y": 816.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "center"
  },
  "header_year_ended": {
    "page": 1,
    "x": 143,
    "y": 799,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "header_quarter_1st": {
    "page": 1,
    "x": 251,
    "y": 804,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "header_quarter_2nd": {
    "page": 1,
    "x": 293.5,
    "y": 803.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "header_quarter_3rd": {
    "page": 1,
    "x": 336.5,
    "y": 804.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "header_quarter_4th": {
    "page": 1,
    "x": 377.5,
    "y": 804.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "header_amended_yes": {
    "page": 1,
    "x": 432,
    "y": 803.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "header_amended_no": {
    "page": 1,
    "x": 474,
    "y": 802.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "header_sheets_attached": {
    "page": 1,
    "x": 569,
    "y": 799,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_tin": {
    "page": 1,
    "x": 228,
    "y": 767.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_rdo_code": {
    "page": 1,
    "x": 554,
    "y": 766.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_taxpayer_name": {
    "page": 1,
    "x": 29.5,
    "y": 737.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_registered_address": {
    "page": 1,
    "x": 29,
    "y": 708,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_zip_code": {
    "page": 1,
    "x": 539.5,
    "y": 690.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_contact_number": {
    "page": 1,
    "x": 28.5,
    "y": 661.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_email": {
    "page": 1,
    "x": 199,
    "y": 660.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_treaty_yes": {
    "page": 1,
    "x": 198,
    "y": 643,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_treaty_no": {
    "page": 1,
    "x": 242,
    "y": 642.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_treaty_specify": {
    "page": 1,
    "x": 370,
    "y": 642.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_tax_rate_graduated": {
    "page": 1,
    "x": 187.5,
    "y": 602,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_tax_rate_8pct": {
    "page": 1,
    "x": 355,
    "y": 602,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_total_tax_due": {
    "page": 1,
    "x": 468.5,
    "y": 565,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_cwt_withheld": {
    "page": 1,
    "x": 468.5,
    "y": 534,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_amended_payment": {
    "page": 1,
    "x": 469,
    "y": 515.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_other_credits": {
    "page": 1,
    "x": 469,
    "y": 497,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_total_credits": {
    "page": 1,
    "x": 469,
    "y": 479,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_tax_still_payable": {
    "page": 1,
    "x": 468.5,
    "y": 461,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_surcharge": {
    "page": 1,
    "x": 469,
    "y": 431.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_interest": {
    "page": 1,
    "x": 469,
    "y": 412,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_compromise": {
    "page": 1,
    "x": 469.5,
    "y": 394.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_total_penalties": {
    "page": 1,
    "x": 469.5,
    "y": 375.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_total_amount_payable": {
    "page": 1,
    "x": 468.5,
    "y": 358,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_overpayment_refund": {
    "page": 1,
    "x": 204,
    "y": 344,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_overpayment_tcc": {
    "page": 1,
    "x": 303,
    "y": 343.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_cash_bank_debit_amount": {
    "page": 1,
    "x": 130,
    "y": 176,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_check_amount": {
    "page": 1,
    "x": 385.5,
    "y": 176,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_tax_debit_memo_amount": {
    "page": 1,
    "x": 131,
    "y": 157,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part3_others_amount": {
    "page": 1,
    "x": 386,
    "y": 157.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "page2_tin": {
    "page": 2,
    "x": 29.5,
    "y": 820.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "page2_taxpayer_lastname": {
    "page": 2,
    "x": 228.5,
    "y": 819,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item1_atc": {
    "page": 2,
    "x": 44,
    "y": 765.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item1_taxable": {
    "page": 2,
    "x": 199.5,
    "y": 763,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item1_tax_rate": {
    "page": 2,
    "x": 327,
    "y": 764,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item1_tax_due": {
    "page": 2,
    "x": 370,
    "y": 764,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item2_atc": {
    "page": 2,
    "x": 42.5,
    "y": 745,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item2_taxable": {
    "page": 2,
    "x": 200,
    "y": 745,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item2_tax_rate": {
    "page": 2,
    "x": 328,
    "y": 746,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item2_tax_due": {
    "page": 2,
    "x": 369.5,
    "y": 746,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item3_atc": {
    "page": 2,
    "x": 43,
    "y": 728,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item3_taxable": {
    "page": 2,
    "x": 200,
    "y": 726.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item3_tax_rate": {
    "page": 2,
    "x": 328,
    "y": 727,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item3_tax_due": {
    "page": 2,
    "x": 369.5,
    "y": 727.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item4_atc": {
    "page": 2,
    "x": 43,
    "y": 708,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item4_taxable": {
    "page": 2,
    "x": 200,
    "y": 708.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item4_tax_rate": {
    "page": 2,
    "x": 328,
    "y": 708,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item4_tax_due": {
    "page": 2,
    "x": 369.5,
    "y": 708.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item5_atc": {
    "page": 2,
    "x": 43.5,
    "y": 690.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item5_taxable": {
    "page": 2,
    "x": 200,
    "y": 690,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item5_tax_rate": {
    "page": 2,
    "x": 328,
    "y": 691,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item5_tax_due": {
    "page": 2,
    "x": 370,
    "y": 692.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item6_atc": {
    "page": 2,
    "x": 44,
    "y": 672.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item6_taxable": {
    "page": 2,
    "x": 201,
    "y": 671.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item6_tax_rate": {
    "page": 2,
    "x": 327,
    "y": 671.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_item6_tax_due": {
    "page": 2,
    "x": 370,
    "y": 672.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "sched1_total_tax_due": {
    "page": 2,
    "x": 370,
    "y": 653.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  }
};
