import type { BirFormCoord } from "./types";

// AUTO-GENERATED by scripts/extract-2551q-coords.ts.
// Visual verification: see tmp/2551Q-coords-check.pdf (and .png if render succeeded).
// Coordinates are pdf-lib convention: origin = bottom-left, y counts up.
// Page size: 612 x 936 pt (US Letter). Reviewed: pending visual check.

export const COORDS_2551Q: Record<string, BirFormCoord> = {
  "header_calendar": {
    "page": 1,
    "x": 130,
    "y": 813.82,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "header_fiscal": {
    "page": 1,
    "x": 205,
    "y": 813.82,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "header_year_ended": {
    "page": 1,
    "x": 125,
    "y": 797.38,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "header_quarter_1st": {
    "page": 1,
    "x": 265.6,
    "y": 800.7,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "header_quarter_2nd": {
    "page": 1,
    "x": 307.1,
    "y": 800.7,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "header_quarter_3rd": {
    "page": 1,
    "x": 350.8,
    "y": 800.7,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "header_quarter_4th": {
    "page": 1,
    "x": 392.2,
    "y": 800.7,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "header_amended_yes": {
    "page": 1,
    "x": 444,
    "y": 797,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "header_amended_no": {
    "page": 1,
    "x": 485,
    "y": 797,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "header_sheets_attached": {
    "page": 1,
    "x": 555,
    "y": 801,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_tin": {
    "page": 1,
    "x": 220,
    "y": 765,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_rdo_code": {
    "page": 1,
    "x": 540,
    "y": 763.66,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_taxpayer_name": {
    "page": 1,
    "x": 285,
    "y": 760.9,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_registered_address": {
    "page": 1,
    "x": 285,
    "y": 731.74,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_zip_code": {
    "page": 1,
    "x": 555,
    "y": 687.1,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_contact_number": {
    "page": 1,
    "x": 210,
    "y": 672.22,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_email": {
    "page": 1,
    "x": 400,
    "y": 672.22,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_treaty_yes": {
    "page": 1,
    "x": 200,
    "y": 639,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_treaty_no": {
    "page": 1,
    "x": 243,
    "y": 639,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_treaty_specify": {
    "page": 1,
    "x": 555,
    "y": 639.07,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part1_tax_rate_8pct": {
    "page": 1,
    "x": 360,
    "y": 597.5,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part1_tax_rate_graduated": {
    "page": 1,
    "x": 190,
    "y": 602.7,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "left"
  },
  "part2_total_tax_due": {
    "page": 1,
    "x": 540,
    "y": 561.67,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_cwt_withheld": {
    "page": 1,
    "x": 540,
    "y": 532.03,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_amended_payment": {
    "page": 1,
    "x": 540,
    "y": 513.79,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_other_credits": {
    "page": 1,
    "x": 540,
    "y": 495.55,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_total_credits": {
    "page": 1,
    "x": 540,
    "y": 477.29,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_tax_still_payable": {
    "page": 1,
    "x": 540,
    "y": 459.05,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_surcharge": {
    "page": 1,
    "x": 540,
    "y": 429.29,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_interest": {
    "page": 1,
    "x": 540,
    "y": 411.05,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_compromise": {
    "page": 1,
    "x": 540,
    "y": 392.81,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_total_penalties": {
    "page": 1,
    "x": 540,
    "y": 374.57,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part2_total_amount_payable": {
    "page": 1,
    "x": 540,
    "y": 356.09,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_cash_bank_debit": {
    "page": 1,
    "x": 540,
    "y": 172.94,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_check": {
    "page": 1,
    "x": 540,
    "y": 154.7,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_tax_debit_memo": {
    "page": 1,
    "x": 540,
    "y": 136.46,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "part3_others": {
    "page": 1,
    "x": 540,
    "y": 121.2,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item1_atc": {
    "page": 2,
    "x": 100,
    "y": 762,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item1_taxable": {
    "page": 2,
    "x": 230,
    "y": 762,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item1_tax_due": {
    "page": 2,
    "x": 480,
    "y": 762,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item2_atc": {
    "page": 2,
    "x": 100,
    "y": 743,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item2_taxable": {
    "page": 2,
    "x": 230,
    "y": 743,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item2_tax_due": {
    "page": 2,
    "x": 480,
    "y": 743,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item3_atc": {
    "page": 2,
    "x": 100,
    "y": 725,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item3_taxable": {
    "page": 2,
    "x": 230,
    "y": 725,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item3_tax_due": {
    "page": 2,
    "x": 480,
    "y": 725,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item4_atc": {
    "page": 2,
    "x": 100,
    "y": 707,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item4_taxable": {
    "page": 2,
    "x": 230,
    "y": 707,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item4_tax_due": {
    "page": 2,
    "x": 480,
    "y": 707,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item5_atc": {
    "page": 2,
    "x": 100,
    "y": 689,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item5_taxable": {
    "page": 2,
    "x": 230,
    "y": 689,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item5_tax_due": {
    "page": 2,
    "x": 480,
    "y": 689,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item6_atc": {
    "page": 2,
    "x": 100,
    "y": 670,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item6_taxable": {
    "page": 2,
    "x": 230,
    "y": 670,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_item6_tax_due": {
    "page": 2,
    "x": 480,
    "y": 670,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  },
  "sched1_total_tax_due": {
    "page": 2,
    "x": 540,
    "y": 652,
    "fontSize": 9,
    "maxWidth": 100,
    "align": "right"
  }
};
